# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='last_hit',
            new_name='last_date',
        ),
        migrations.RemoveField(
            model_name='hit',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='hit',
            name='last_ip_address',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
