# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170505_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='last_date',
            new_name='last_hit',
        ),
        migrations.RemoveField(
            model_name='hit',
            name='last_ip_address',
        ),
        migrations.AddField(
            model_name='hit',
            name='ip_address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
